### ISSUE TITLE
ts文件在第二层m3u8的下载不了

### ISSUE THREAD

**Issue by fjpan2023** [qq494257084/m3u8Download#2]

**Comment by fjpan2023** [comment]
如题，m3u8地址：http://livecdn.pull.cdbs.com.cn/live/fm963/playlist.m3u8

**Comment by qq494257084** [comment]
你好，你的m3u8地址的第二层“http://livecdn.pull.cdbs.com.cn/live/fm963/playlist.m3u8?wsSession=...”，
带有请求参数wsSession的才是真正的m3u8链接，可以手动请求一次m3u8，然后拿到这个url，再用M3u8Download下载。
