### ISSUE TITLE
合并问题

### ISSUE THREAD

**Issue by diorslau** [qq494257084/m3u8Download#3]
你好  是否能加一个下载后不合并ts的方法呢

**Comment by qq494257084** [comment]
你好，你可以将net.m3u8.download包下M3u8DownloadFactory 类的startDownload方法中的 mergeTs()此行代码（156行）注释掉

**Comment by qq494257084** [comment]
然后也把其后面的 deleteFiles（158行）给注释掉。然后下载目录中的xy后缀文件都删掉，留下来的xyz后缀的即是所需要的ts片段。
