### ISSUE TITLE
你好，合并后无法打开，会是什么原因

### ISSUE THREAD

**Issue by zzzzzmh** [qq494257084/m3u8Download#5]
https://videozmcdn.stz8.com:8091/20191127/PK7a0LKQ/index.m3u8 
你好，测试代码的这个地址，合并成 mp4文件，无法打开，会是什么原因呢？

**Comment by zzzzzmh** [comment]
用暴风影音可以播放，mac的quicktime player播放不了。
播放过程中，会有卡顿的现象。

**Comment by qq494257084** [comment]
这个m3u8合并后mp4播放的解码方式和普通mp4解码方式不一样，quicktime player需要安装额外的解码器
