### ISSUE TITLE
合并完成的视频无法直接预览

### ISSUE THREAD

**Issue by jw-star** [qq494257084/m3u8Download#9]
当发送合并的视频到微信，合并完成的视频无法直接预览

**Comment by qq494257084** [comment]
这个m3u8合并后mp4播放的解码方式和普通mp4解码方式不一样，需要转换成其他解码器支持的mp4格式之后才能预览

**Comment by jw-star** [comment]
> 这个m3u8合并后mp4播放的解码方式和普通mp4解码方式不一样，需要转换成其他解码器支持的mp4格式之后才能预览

嗯嗯，已经用ffmpeg做了格式转换。

**Comment by jw-star** [comment]
.
